- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Aspid
  - Amber
  - Bagel
  - Box
  - Cog
  - Core
  - Fland
  - Gemini
  #- Gate
  - Loop
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Packed
  - Reach
  #- Train <- CD change, please no
  - Ferrous
