- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Aspid
  - Bagel
  - Box
  - Cog
  - Core
  - Fland
  - Gemini
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Origin
  - Packed
  - Reach
  #- Train <- CD change, please no
  - Ferrous
